'use strict';

module.exports = {
    ENOTSOCK: 'Socket operation on non-socket',
    EDESTADDRREQ: 'Destination address required',
    EMSGSIZE: 'Message too long',
    EPROTOTYPE: 'Protocol wrong type for socket',
    ENOPROTOOPT: 'Protocol not available',
    EPROTONOSUPPORT: 'Protocol not supported',
    ESOCKTNOSUPPORT: 'Socket type not supported',
    EOPNOTSUPP: 'Operation not supported on transport endpoint',
    EPFNOSUPPORT: 'Protocol family not supported',
    EAFNOSUPPORT: 'Address family not supported by protocol',
    EADDRINUSE: 'Address already in use',
    EADDRNOTAVAIL: 'Cannot assign requested address',
    ENETDOWN: 'Network is down',
    ENETUNREACH: 'Network is unreachable',
    ENETRESET: 'Network dropped connection because of reset',
    ECONNABORTED: 'Software caused connection abort',
    ECONNRESET: 'Connection reset by peer',
    ENOBUFS: 'No buffer space available',
    EISCONN: 'Transport endpoint is already connected',
    ENOTCONN: 'Transport endpoint is not connected',
    ESHUTDOWN: 'Cannot send after transport endpoint shutdown',
    ETOOMANYREFS: 'Too many references: cannot splice',
    ETIMEDOUT: 'Connection timed out',
    ECONNREFUSED: 'Connection refused',
    EHOSTDOWN: 'Host is down',
    EHOSTUNREACH: 'No route to host',
    EALREADY: 'Operation already in progress',
    EINPROGRESS: 'Operation now in progress',
    EREMOTEIO: 'Remote I/O error',
    ECANCELED: 'Operation Canceled'
};
